### ISSUE TITLE
SCSS - columns margin should be calculated using $gutter value

### ISSUE THREAD

**Issue by ilu2112** [zachacole/Simple-Grid#16]
Check https://github.com/zachacole/Simple-Grid/blob/master/simple-grid.scss#L133:

```scss
.row [class^="col"] {
  float: left;
  margin: 0.5rem 2%;
  min-height: 0.125rem;
}
```

I guess You should change `2%` in `margin: 0.5rem 2%;` to `($gutter / 2)`. Am I right?
